name: Deploy Doc

on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build:docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: deployment

      - name: Deploy Doc
        run: GIT_USER=${{ secrets.USERNAME }} yarn deploy:doc
        env:
          GIT_USER: ${{ secrets.USERNAME }}
          GIT_PASS: ${{ secrets.PAT }}
